"""initial create users, currency, transactions

Revision ID: 258b36cca6bc
Revises: 
Create Date: 2025-06-01 12:59:05.211436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258b36cca6bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','completed','failed')", name='ck_transactions_status_valid'),
    sa.CheckConstraint('amount >= 0', name='ck_transactions_amount_nonnegative'),
    sa.ForeignKeyConstraint(['currency'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('idx_transactions_receiver', 'transactions', ['receiver_id'], unique=False)
    op.create_index('idx_transactions_sender', 'transactions', ['sender_id'], unique=False)
    op.create_index('idx_transactions_suspicious', 'transactions', ['is_suspicious'], unique=False, postgresql_where=sa.text('is_suspicious = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_suspicious', table_name='transactions', postgresql_where=sa.text('is_suspicious = true'))
    op.drop_index('idx_transactions_sender', table_name='transactions')
    op.drop_index('idx_transactions_receiver', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_table('currency')
    # ### end Alembic commands ###
